---
title: "Lab 00 - Hello IDS!"
author: "Mariam"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Layla", "Ruaraidh", "Omar", 
           "Sam", "Emiliam"),
  github_username = c("laylawed", "ruariadh27", "Omari0s", 
                      "SamLawrie", "emiliawalker123"), 
  colour = c("purple", "magenta", "steelblue", 
             "orange", "brown"),
  hobby = c("Running", "swimming", "guitar", 
            "skipping", "tennis"),
  favourite_number = c(6, 2, 4, 5, 3)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

This plot shows a bar chart with each person username on the x-axis against their favourite number on the y-axis, with the colour of each bar representing their favourite colour

